<?php

namespace Container8Z4lQB5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationEvenementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.H1ST4JL.App\Entity\ReservationEvenement' shared service.
     *
     * @return \App\Entity\ReservationEvenement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.H1ST4JL": it needs an instance of "App\\Entity\\ReservationEvenement" but this type has been excluded in "config/services.yaml".');
    }
}
