<?php

namespace Container2nRxZXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TaGyL4JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TaGyL4J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TaGyL4J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.TaGyL4J.App\\Entity\\ReservationEvenement', NULL, 'Cannot autowire service ".service_locator.TaGyL4J": it needs an instance of "App\\Entity\\ReservationEvenement" but this type has been excluded in "config/services.yaml".'],
            'utilisateurRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'reservation' => 'App\\Entity\\ReservationEvenement',
            'utilisateurRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
