<?php

namespace Container2nRxZXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5YMg5IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5_yMg5I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5_yMg5I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evenementRepository' => ['privates', 'App\\Repository\\EvenementRepository', 'getEvenementRepositoryService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationVoyageRepository', 'getReservationVoyageRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'voyageRepository' => ['privates', 'App\\Repository\\VoyageRepository', 'getVoyageRepositoryService', true],
        ], [
            'evenementRepository' => 'App\\Repository\\EvenementRepository',
            'reservationRepository' => 'App\\Repository\\ReservationVoyageRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'voyageRepository' => 'App\\Repository\\VoyageRepository',
        ]);
    }
}
