<?php

namespace Container2nRxZXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GHDWrdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G_hDWrd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G_hDWrd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.G_hDWrd.App\\Entity\\ReservationVoyage', NULL, 'Cannot autowire service ".service_locator.G_hDWrd": it needs an instance of "App\\Entity\\ReservationVoyage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\ReservationVoyage',
        ]);
    }
}
