<?php

namespace Container2nRxZXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LxbdZnfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LxbdZnf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LxbdZnf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'reservation' => ['privates', '.errored..service_locator.LxbdZnf.App\\Entity\\ReservationVoyage', NULL, 'Cannot autowire service ".service_locator.LxbdZnf": it needs an instance of "App\\Entity\\ReservationVoyage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'reservation' => 'App\\Entity\\ReservationVoyage',
        ]);
    }
}
