<?php

namespace Container2nRxZXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationVoyage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LxbdZnf.App\Entity\ReservationVoyage' shared service.
     *
     * @return \App\Entity\ReservationVoyage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LxbdZnf": it needs an instance of "App\\Entity\\ReservationVoyage" but this type has been excluded in "config/services.yaml".');
    }
}
