<?php

namespace Container2nRxZXL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoyageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cRw86ao.App\Entity\Voyage' shared service.
     *
     * @return \App\Entity\Voyage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cRw86ao": it needs an instance of "App\\Entity\\Voyage" but this type has been excluded in "config/services.yaml".');
    }
}
